mutation Auth($loginUserInput: LoginUserInput!) {
  login(loginUserInput: $loginUserInput) {
    user {
      id
      name
    }
    id_token
  }
}

query getCurrentUser {
  currentUser {
    id
    username
    name
  }
}
