mutation CreateCat($input: CreateCatDto!) {
  createCat(input: $input) {
    name
    age
    breed
    id
  }
}

query GetMyCats {
  myCats {
    name
    age
    breed
    id
  }
}

query GetCats {
  cats {
    name
    age
    breed
    id
    userId
  }
}

mutation DeleteCat($CatId: String!) {
  deleteCat(input: $CatId) {
    name
  }
}

query GetUsers($Ids: [ID!]!) {
  usersById(Ids: $Ids) {
    name
    username
    id
  }
}
